a = 'Hello world!'.startswith('Hello')
print(a)
a = 'Hello world!'.endswith('woeld!')
print(a)
a ='abc123'.startswith('abcdef')
print(a)
a = 'abc123'.endswith('12')
print(a)
a = 'Hello world!' .startswith('Hello world!')
print(a)
a = 'Hello world!' .endswith('Hello world!')
print(a)

a ='Hello'.rjust(10)
print(a)
a ='Hello'.rjust(20)
print(a)
a ='Hello World'.rjust(20)
print(a)
a ='Hello'.ljust(10)
print(a)
a ='Hello'.rjust(20,'*')
print(a)
'Hello'.ljust(20,'-')
print(a)
a ='Hello'.center(20)
print(a)
a ='Hello'.center(20,'=')
print(a)